server:
  port: 9000
#jdbc related properties
#jdbc url
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management_tracker
    username: root
    password: root@123
    driver-class-name: com.mysql.jdbc.Driver
#username
#password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      properties:
      javax:
        persistence:
          validation:
            mode: none